---
title: "URAP Position"
author: "Carl Boettiger, Scott Chamberlain"
date: "8/2/2017"
output: html_document
---

## Title

"Data Science Software Development & Applications in Ecology and the Environment"


## General description of the project (the concept):


Get involved on the front line of data science research in the R language with rOpenSci (<https://ropensci.org>).  rOpenSci develops and maintains a wide ranging suite of software to access and manipulate heterogeneous scientific data sources.  Despite the rapid expansion of available data in fields such as ecology and environmental science, 

This semester, student researchers will work closely with the faculty adviser and other members of the rOpenSci team to design and implement a JSON-LD based metadata model describing the data sources and the software packages used to access them.  This system will improve search and discovery of relevant data and software.  

Students will also learn and be involved in the fundamentals of software maintenance and development, including such issues as unit testing and continuous integration, interactive software documentation, etc.


## Specific role for the undergraduate (tasks and learning outcomes):

Students will learn essential skills of data science and software development not usually taught in classes while working collaboratively with the rOpenSci team. Through this project, students will learn the following tools and technologies:

- GitHub: git flow, pull requests, GitHub API use
- R: Package development, documentation, testing
- JSON-LD: linked data principles, schema.org descriptions, parsing, serialization & validation


## Specific qualifications the student should have:

Candidates should be self-motivated, curious, and able to collaborate effectively & professionally in an online environment.  Prior experience with GitHub and some previous programming experience in any language are strongly recommended.  




## Hours per week of commitment required:

- [ ] 3-6 hrs
- [ ] 6-9 hrs
- [ ] 9-12 hrs
- [ ] more than 12 hrs
- [x] to be negotiated

## The research site is

On Campus

## Website URL 1:  

<https://ropensci.org>

